#!/bin/bash
echo '#!/bin/bash' > 5-execute
echo '#!/bin/bash' > 6-multiple_permissions
echo '#!/bin/bash' > 7-everybody
echo '#!/bin/bash' > 8-James_Bond
echo '#!/bin/bash' > 9-John_Doe
echo '#!/bin/bash' > 10-mirror_permissions
echo '#!/bin/bash' > 11-directories_permissions
echo '#!/bin/bash' > 12-directory_permissions
echo '#!/bin/bash' > 13-change_group
