#!/usr/bin/env bash
#Script that displays bad luck for 4 and 8 best for 8
num=0
while [ $num -lt 10 ];
do
        if [ $num -eq 3 ]
        then
echo "bad luck"
        elif [ $num -eq 7 ]
        then
echo "good luck"
	else
        echo "Best School"
	fi
	(( num++ )) || true
done
