#!/usr/bin/env bash
#Script that displays bad luck for 4 and 8 best for 8
num=0
while [ $num -lt 10 ];
do
        if [ $num -eq 3 ]
        then
echo "bad luck"
        fi
	if [ $num -eq 7 ]
        then
echo "good luck"
        fi
        echo "Best School"
        (( num++ )) || true
done
